### ISSUE TITLE
Compatibility with analyzer

### ISSUE THREAD

**Issue by gromanssp** [channdara/flutter_localization#20]
I am updating my flutter project to 3.22.0 and have compatibility issues with flutter_localizations The error is as follows: Because analyzer >=6.5.1 depends on meta 1.15.0 and analyzer >=6.5.0 <6.5.1 depends on meta 1.14.0, analyzer >=6.5.0 requires meta 1.14.0.
(1) So, because every version of flutter_localizations from sdk depends on meta 1.12.0, flutter_localizations from sdk is incompatible with analyzer >=6.5.0.

**Comment by channdara** [comment]
Hello @gromanssp and sorry for the late reply.

The issue you're facing is caused by the Flutter SDK [flutter_localizations](https://api.flutter.dev/flutter/flutter_localizations/flutter_localizations-library.html)
Unfortunately, you probably need to report this issue to the [Flutter](https://github.com/flutter/flutter/issues) repository.
